"""Prompt Library

Revision ID: fa491e6ea7d0
Revises: bb4e674bd910
Create Date: 2025-05-19 09:23:17.579199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa491e6ea7d0'
down_revision: Union[str, None] = 'bb4e674bd910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prompts_pkey'),
    sa.UniqueConstraint('prompt_name', name='prompts_prompt_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
